- chemprop/train/run_training.py
This commit fixes a issue that If only separate validation set is provided, the resulting test set would be null.
> BugFix: Correctly split dataset if only separate validation set provided

- README.md
The link to "aicures.mit.edu" in the COVID-19 section did not have a "https://" in front of it, so the link went to "https://github.com/chemprop/chemprop/blob/master/aicures.mit.edu" instead of "https://aicures.mit.edu".
> Fixed broken link to aicures.mit.edu

- chemprop/models/mpn.py
Hi,
Apparently we don't need keeping training arguments in MPN models. Besides, keeping them may cause issues with saving those models using pickle.
> Don't save args in MPN/MPNEncoder

- chemprop/data/utils.py
- chemprop/train/run_training.py
Hello!
First, huge fan of ChemProp. Thanks for open sourcing such great code. 
I was running ChemProp on particular tasks in the ChEMBL dataset (using --target_columns) and observed that sometimes my losses would explode or be NaN -- after digging through what was going on I realized that I was running into an edge case where, as ChEMBL is a sparse dataset, several of the datapoints in the chembl.csv dataset are irrelevant to the specified --target_columns at hand, so unlabelled datapoints were being surfaced during training.
I fixed the issue with this 3-liner. I hoped this was the simplest fix that wouldn't break other functionality, but let me know if this doesn't play well with other uses of ChemProp (e.g. when running on other datasets).
Thanks again!
> Change to get_data to skip irrelevant examples when filtering with target_columns

- chemprop/data/data.py
Program may hang when torch DataLoader with multiple workers is used in a subprocess. Please see a huge comment to the torch.utils.data.dataloader._MultiProcessingDataLoaderIter class for references (near line 465 depending on your version). This problem can be solved by using another multiprocessing context. In order to enable GPU I would recommend to use the 'forkserver' context (https://pytorch.org/docs/stable/notes/multiprocessing.html). 
There is no need to use this context in case the MoleculeDataLoader is used by the main process or number of workers is zero. So, I added this check also.
/Cheers,
Artem
> Using DataLoader in a subprocess. Fixed freezing.

- chemprop/args.py
- chemprop/data/data.py
- chemprop/data/utils.py
- chemprop/features/__init__.py
- chemprop/features/featurization.py
- chemprop/features/utils.py
- chemprop/models/model.py
- chemprop/models/mpn.py
- chemprop/train/cross_validate.py
- chemprop/train/predict.py
- chemprop/train/run_training.py
- chemprop/train/train.py
- tests/test_integration.py
This merge allows custom atomic features (a counterpart of the custom molecule features). The atomic features can be embedded in two ways: 1) as extra atom features during the molecule featurization. 2) as atomic descriptors that concatenated to the atomic feature vector after MPNN. The custom atomic feature is used through flag --atom_descriptors.
> Custom Atom features

- chemprop/args.py
- chemprop/utils.py
- scripts/split_data.py
Hi everyone,
I have a small pull request that adds binary cross entropy as a metric. It also fixes the bug that split_sizes were expected to be integers instead of floats in split_data.py (I know this bug was already fixed in args.py, but I don't think it was fixed in the script).
Let me know what you think!
Simon
> Binary cross entropy as a metric function and split_sizes bug fix

- chemprop/data/utils.py
- chemprop/features/__init__.py
- chemprop/features/utils.py
custom atomic descriptors can be put in through `.sdf` and `.npz`. The original `.pkl` input that stores a dataframe may cause error when a different version of Pandas was used to prepare the `.pkl`.
> update support for custom atomic descriptors in format of `.sdf` and `.npz`

- chemprop/features/featurization.py
- chemprop/train/make_predictions.py
We found when using custom atomic features in the "feature" mode, the predict.py fails due to an error in setting EXTRA_ATOM_FEATURE in the featurization. The bug was fixed in this pull request.
> Atom features

- chemprop/utils.py
Closes #106 observed that logs (verbose or quiet) are no longer being written by chemprop. The failure is coming in `create_logger()` when checking to see if the specified logger already exists. Previously, `logging.getLogger()hasHandlers()` worked as a way to see if a log had been previously initiated, but its default return is True now instead of False. Not clear what changed that behavior, but it looks like the logging root has a handler `stderr` by the time this function is run that it detects. As an alternative now, running the check to see if the specified logger exists by seeing if it is in `logging.root.manager.loggerDict`. This appears to have reenabled logging.
> Fix check if logger already exists

- README.md
- chemprop/interpret.py
- docs/source/tutorial.rst
Fixed a bug in interpret.py. The mcts and mcts_rollout functions expect a smiles string, but Chemprop expects a list of smiles after we included multiple molecules in summer.
Am now checking if we have only one molecule (otherwise raise a ValueError), and fixed the list vs. str issue in two lines.
> fixing smiles list error in interpret.py

- README.md
`--number-of-molecules` corrected to `--number_of_molecules` once
`--aggregration` corrected to `--aggregation` twice
> Fixed a few typos in arguments listed in the README

- chemprop/features/featurization.py
Just confirmed a bug when using atom messages: 
We set up the bond features in the order atom(length 133)-bond(length 14):
https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L171-L172
but then cut out the first (!) 14 values, instead of the last:
https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L267-L270
Have added a few print statements, and we indeed used the wrong features for atom messages (which are the first 14 one-hot encoded elements, and thus rather meaningless). I have corrected this bug by simply cutting out the last values instead of the first (alternatively, we could change the order of setting up the bond vectors, but this would not be …
> bugfix for atom meassages concerning bond feature vector

- chemprop/args.py
- chemprop/data/__init__.py
- chemprop/data/utils.py
- chemprop/sklearn_train.py
- chemprop/train/cross_validate.py
- chemprop/train/make_predictions.py
- chemprop/train/run_training.py
- chemprop/utils.py
- chemprop/web/app/views.py
- scripts/class_balance.py
- scripts/create_crossval_splits.py
- scripts/find_similar_mols.py
- scripts/overlap.py
- scripts/split_data.py
This PR consolidates the logic checks and changes to `args.smiles_columns` in one function and applies it during argument processing. These checks and changes are now held within an expanded `preprocess_smiles_columns` in `chemprop.data.utils`. The redundant checks and changes have been removed from other code locations.
For normal function of chemprop, `preprocess_smiles_columns` will be run during argument processing before `args.smiles_columns` is referenced anywhere in the code. This simplifies references to `args.smiles_columns` by enforcing that it contains a list of strings corresponding to the header of the data file from early on.
The changes to `smiles_columns` consolidated into the `preprocess_smiles_columns` function, with the previous locations for the changes in parentheses: …
> Smiles processing

- README.md
- chemprop/models/model.py
- chemprop/train/__init__.py
- chemprop/train/make_predictions.py
- chemprop/train/molecule_fingerprint.py
- fingerprint.py
- setup.py
I added a new function that saves the fingerprint vector for a set of provided molecules. The function mirrors what is going on in predictions, except that the output is what is provided by the MPN before it runs through the FFN (excludes features concatenated onto the vector).
The function works through the command line (when `pip install -e .` is run again) and when using two molecules.
Brief explanation of the file changes:
- Readme - Add explanation for the new function
- chemprop.data.utils - Saves the names of the smiles columns used in the get_data step even if the columns are not provided in the initial arguments.
- chemprop.models.model - Adds a class function to MoleculeModel that returns the MPNN output without passing it through the FFN.
- chemprop.train.molecule_fingerprint - …
> New Function - Save the latent representation for a molecules

- scripts/find_similar_mols.py
Simple bug fix for tanimoto measure introduced after changes for multiple molecules. 
The other distance measures are not affected (I ran some tests).
Note that this function does not work for multiple molecules or for extra features (mol, atom and bond). There are currently no checks or warnings.
> Fix bug for tanimoto distance measure

- README.md
- chemprop/args.py
- chemprop/train/make_predictions.py
I added the ability to calculate the epistemic uncertainty of predictions using `--ensemble_variance`. This writes the uncertainty as a separate column in the predictions file. I made the corresponding changes to the README. I tested this on training/predicting with the following:
1. single model, 1 molecule, 1 target
2. single model, 2 molecules, 1 target
3. ensemble model, 1 molecule, 1 target
4. ensemble model, 2 molecules, 1 target
5. ensemble model, 2 molecules, 2 targets
> Epistemic uncertainty

- chemprop/train/make_predictions.py
- chemprop/train/molecule_fingerprint.py
- chemprop/utils.py
Fix for #148. This PR adds a function that fills in the default values for training args when those training args are missing in the checkpoint file. This bridges a backwards compatibility issue introduced at #137.
> Backwards compatibility for Missing Training Args

- chemprop/models/mpn.py
This fixes the type annotation for `MPN.forward` and the corresponding docstring. 
`forward` cannot receive a single BatchMolGraph instance as its batch argument with the current implementation.
An alternative fix would be to add this line before line 204:
```if type(batch) == BatchMolGraph: batch = [batch]```
and to have both `BatchMolGraph` and `List[BatchMolGraph]` as valid types for `batch`. If you prefer I do that fix I can delete this pull request and pull request [this branch](https://github.com/bengioe/chemprop/blob/mpn_fix/chemprop/models/mpn.py) instead. I'm not familiar with chemprop so I don't know if that would be a bad change.
This alternative fix would also make chemprop backwards compatible, as c6dee25c breaks this behavior (because of …
> Fix type annotations for MPN.forward

- chemprop/models/mpn.py
The author of issue #153 correctly noted that for checking the dimensions of `batch` in the MPN forward pass, there is a small bug when checking the dimensions of the batch for multiple-molecule input (the check is needed to raise an error when multi-molecule input is combined with custom atom/bond features, which is currently not supported) - the current code wrongly checks the batch size (the dimension of the inner list) instead of `args.number_of_molecules` (the dimension of the outer list) to be 1. I corrected this, and added a description to the docstring about which dimension is which.
Since this is connected to atom/bond descriptors, could you take a look, @fhvermei.
> bugfix for batch dimensions in mpnn forward pass

- scripts/create_crossval_splits.py
Another bug fix for multi-molecule input. This is analogous to the changes that were made in [2c98bf7](https://github.com/chemprop/chemprop/commit/2c98bf743cf90893dcc7b9f2b70786a2c7735b2f) (checking if multi-molecule input is used, raise an exception, else flatten the list of molecules).
> bugfix for multi-molecules in scaffold split

- README.md
- chemprop/train/run_training.py
- chemprop/utils.py
Resolves #157 . As part of `--save_smiles_splits`, a pickle file is saved with the indices in the data file that are associated with each of the train/val/test splits. This listing of indices is inappropriate when there are more than one data file, such as when `--separate_test_path` is specified. Also, this listing of indices is constructed after-the-fact by matching SMILES in the splits to the data file, and so cannot easily distinguish between entries in the data file with the same SMILES. This PR adds a warning if either of these conditions are met and skips writing the pickle file.
> Bypasses Pickle index file when repeated SMILES or multiple data paths

- README.md
- docs/source/tutorial.rst
Added information in the readme and the documentation (as requested) on:
- pretraining
- treatment of missing values in multitask models
- caching
as well as added the description of the reaction mode to the documentation (which was already in the readme).
> update readme and docs

- chemprop/train/evaluate.py
When performing multiclass training, there is a problem with the call of
`accuracy` metric where the `labels` argument is incorrectly passed to
the function, throwing an error.
> Fix unknown keyword argument passed to accuracy in train.evaluate.

- chemprop/interpret.py
RDKit version >= 2021.03.01 changes the default behavior of how molecule fragments are kekulized (and how failures are treated, previously resulting in a None smiles string, now in an exception being raised), leading to an incompatibility with the interpretation script in Chemprop (see #178). 
I have discussed with Wengong on the best way to fix this, he agreed on adding a try/except clause. This is compatible with all rdkit versions, including new ones. 
On a side note: The default behaviour of rdkit changed due to a bugfix, which involves fragments being incorrectly kekulized - I am therefore not sure whether new versions of rdkit might lead to slightly different results in the interpretation scripts regardless of the fix proposed here (for all tests I ran, the results were the same, …
> bugfix new rdkit version

- chemprop/train/cross_validate.py
Currently, tap causes an issue when training a model within a git repo that has no origin specified. To reproduce the error:
`mkdir test; cd test; git init`
`python <path_to_chemprop>/train.py --data_path <path_to_data_csv> --dataset_type regression`
This is a tap issue since when writing arguments to file, it runs `git remote get-url origin`, in the current folder, not in the chemprop folder (which would be correct). I will open a tap issue too, but to stay compatible with older versions of tap (and until they fix it), I think it would be good to have a workaround.
> bugfix for training within git repo

- README.md
- chemprop/train/__init__.py
- chemprop/train/make_predictions.py
- docs/source/tutorial.rst
As discussed, here is an (initial, unfinished) PR of enabling model preloading. To test, run a script like:
```python
import chemprop
import time
smiles = [
['CC(C)C(C)(C)C'],
['Clc1ccc(c(Cl)c1Cl)c2c(Cl)cc(Cl)c(Cl)c2Cl'],
]
arguments = [
'--test_path', '/dev/null',
'--preds_path', '/dev/null',
'--checkpoint_paths', 'model.pt', #change to your model file or files, or use checkpoint_dir if needed
]
args = chemprop.args.PredictArgs().parse_args(arguments)
print(args)
time1=time.time()
for i in range(100):
preds = chemprop.train.make_predictions(args=args, smiles=smiles)
time2=time.time()
print(time2-time1)
print(preds)
time1=time.time()
model_args = chemprop.train.load_model(args=args)
for i in range(100):
preds = chemprop.train.make_predictions(args=args, smiles=smiles, …
```
> Enable preloading of a model

- chemprop/features/__init__.py
- chemprop/features/featurization.py
- chemprop/train/cross_validate.py
- chemprop/train/make_predictions.py
- chemprop/train/molecule_fingerprint.py
- tests/test_integration.py
This PR is after PR #197. Fixes the vector length conflicts in testing caused by running multiple trainings of different types serially in one script.
Changed the global parameters in `featurization.py` to be attributes of a class `Featurization_parameters`. Added a function for resetting the global featurization parameters which is called early in `cross_validate`, `make_predictions`, and `molecule_fingerprints`. Function could also be called separately in python api usage.
There may be a more preferred stylistic approach. Also unclear if the reset function should be added to the `interpret.py` file.
> Global featurization params

- README.md
- chemprop/__init__.py
- chemprop/args.py
- chemprop/constants.py
- chemprop/hyperopt_utils.py
- chemprop/hyperparameter_optimization.py
Added checkpoint functions hyperparameter optimization to allow hyperopt to 1) be restarted after failing 2) start again after normal termination but adding additional iterations, and 3) run with multiple instances in parallel adding checkpoints to the same directory. Also added a feature to change the number of random iterations before guided suggestions are supplied.
Potential to add an additional feature to make trial histories out of previous runs that were done outside of hyperopt, but that has more edge cases with weird behavior than these other features so am leaving this off for now.
> Parallel hyperopt

- chemprop/rdkit.py
Fix for adding_h option making explicit_h (keeping hydrogens from input smiles) and adding_h (adding hydrogens to input smiles) separate, as we might need both for some edge cases in reaction mode.
> correction adding_h option

- chemprop/train/make_predictions.py
When using models to predict on a multiclass task or several tasks if the smiles are invalid then they are replaced with a list containing 'Invalid SMILES' as the number of tasks.
Then when the tasks are multiclass it tries to reshape the list from a 2-dimensional array shape: (num_tasks, num_classes) to a 1-d array but press contains a list and not a ndarray anymore. This raises a value and prevents using chemprop_predict on multiclass tasks with SMILES that may be invalid.
I added a simple check before executing the reshape to check if preds is a ndarray and if the number of dimensions it has is larger than one so we'll not reshape an already 1-d array.
> Fixed reshape error for invalid smiles

- chemprop/data/__init__.py
- chemprop/data/utils.py
- chemprop/train/make_predictions.py
User noted that for the make_predictions function, invalid SMILES can be included in the arguments but the returned values will exclude the invalid entries without any notation of which ones are invalid. The default behavior before for the values saved to file has always been to include the entries with invalid SMILES with prediction values of "Invalid SMILES". Following the refactoring of make_predictions in #200, it's more accessible than before to use this function directly and so it's now more obvious that the saved behavior and the function return behavior do not match.
I've added two new options to the make_predictions function.
- `return_invalid_smiles`. This option indicates whether to include predictions for invalid datapoints, with the value "Invalid SMILES" in the function …
> Output options for make_predictions

- chemprop/hyperparameter_optimization.py
Newest version of hyperopt (0.2.7) did away with support for a deprecated way of doing numpy random integer generation. This PR updates the way that the random state is passed into hyperopt to be in line with the up-to-date random integer generation. Will resolve #243.
Edit: have changed the seed submission to use an environment variable to provide the seed instead and not provide the numpy object directly.
> Update away from deprecated numpy random integer generation

- chemprop/data/data.py
- chemprop/data/scaffold.py
- chemprop/data/utils.py
- chemprop/nn_utils.py
- chemprop/sklearn_predict.py
- chemprop/train/make_predictions.py
- chemprop/train/molecule_fingerprint.py
This PR removes some of the `assert`s in the codebase that were used to validate function inputs and has replaced them with `ValueError`s. `assert`s are fine for sanity checking output, but should generally be avoided as they slow down code and can typically be replaced by more appropriate error checking.
This PR **does not** add new validation code. It just changes any `assert`s that were clearly for argument validation to `ValueError`s. There are a few `TODO`s in this PR too because there were some `assert`s that are more accurately described as unit tests.
> remove `assert`s

- chemprop/args.py
- chemprop/data/data.py
- chemprop/data/utils.py
- chemprop/train/run_training.py
Previously, chemprop could not be run with an empty test set, except in the narrow situation where it was triggered by splitting according to `cv-no-test`. A recent change created an error in the operation with `cv-no-test`as noted in #260 and #279. This PR makes several changes that affects the `cv` and `cv-no-test` splits and empty test set splits generally.
- creates a logic check for whether a dataset is empty that bypasses evaluation and prediction steps
- removes a requirement that the test set size in provided `--test_set_sizes` be nonzero
- changes the algorithm for `cv` and `cv-no-test` to address a problem where data splits could vary by more than +/- 1 datapoint between folds.
```
chemprop_train \
--data_path path/to/data.csv \
--dataset_type regression \
--split_type …
```
> Allow for Running With Empty Test Set and Fix `cv-no-test`

- README.md
- chemprop/train/cross_validate.py
- chemprop/train/run_training.py
- chemprop/utils.py
- tests/test_integration.py
- tests/test_unit/test_loss_functions.py
In multitask models, the metric used for whole model evaluation is an average of the different tasks. This is then used in evaluating the best epoch and for providing the overall test set performance as used in hyperparameter search. The problem is that the metric evaluation is carried out on non-scaled targets, so in regression models the largest magnitude target will dominate for most metrics.
In this PR, I've made the change that when the metric is magnitude-dependent, geometric mean is used instead of arithmetic mean. This bypasses the scale difference by weighing the changes in individual task metrics in a relative sense (10% improvement on task A is worth the same as 10% on task B, no matter the scale).
I've also removed the averaging functions that filter out nan values from the …
> Multitask Evaluation on Different Magnitude Targets

- chemprop/uncertainty/uncertainty_calibrator.py
Previously, the mve_weighting calibration method that can be used on ensembles of mve or evidential trained models did not work for multitask models. The optimization step took in shape(num_models) fitting parameters and returned shape(num_tasks) loss values. These were used with `fmin` which is incompatible with multiple returned values.
To fix this, I summed the output losses together so that it was a single output value. Because these losses were negative log likelihood values, summing them together is the equivalent of treating them like joint distributions, and is a sensible way to aggregate the values.
Placing as a PR for atom-bond-targets because including a version of mve_weighting that worked with atom targets was awaiting this bug fix. And will subsequently be rolled into master …
> Bugfix for multitarget mve_weighting calibration

- chemprop/uncertainty/uncertainty_evaluator.py
- tests/test_integration.py
The `ence` uncertainty evaluation method contained a bug where an unassigned variable was called unnecessarily. It triggered when a calibration method was used with a stdev metric. Have corrected this and added a unit test covering this combination. Also noticed that the variable assignment wasn't set up right for the calibration method `tscaling` in combination with `ence` and corrected this as well.
Bug present when used with `--calibration_method {any} --regression_calibration_metric stdev --uncertainty_evaluation_methods ence`.
Addresses #301
> Rearrange ence evaluation

- chemprop/train/loss_functions.py
- tests/test_unit/test_loss_functions.py
Fix our implementation of multiclass Matthews correlation coefficient (MCC) loss function to give results that match sklearn and add unit tests for this.
This addresses [Issue 306](https://github.com/chemprop/chemprop/issues/306). I originally thought that the only problem was with the loss being infinite when all predictions and/or all targets were the same. My original plan was to raise a `ValueError` in this case and recommend that the user choose a different loss function. However, while writing unit tests for this, I realized that our existing implementation of MCC did not give the same results as [sklearn's implementation](https://scikit-learn.org/stable/modules/model_evaluation.html#matthews-corrcoef), even for normal cases. I also saw that sklearn's …
> Fix multiclass MCC loss function

- README.md
- chemprop/args.py
This PR intends to add some more description to evidential regularization. This option was not previously mentioned in the readme file.
Issue #352 asks about the reason for the default value for evidential regularization being 0.0. In doing so, points out that the wrong default value was attributed to the source literature paper, Soleimany et al.(2021). This has been corrected in this PR.
> Add to the description of evidential regularization

- chemprop/data/scaffold.py
- scripts/examine_split_balance.py
Numpy has deprecated the `np.float` data type as an unnecessary duplicate of the base python `float` type. As of numpy version 1.24, this data type is no longer supported and will cause errors during running or testing. This appears to be the cause of the error in testing currently on the main branch; testing on the last PR showed passing because it was tested with an older version of numpy.
This PR replaces `np.float` with `float` in the two instances in Chemprop where it was used.
> Remove deprecated numpy float types

- chemprop/uncertainty/uncertainty_evaluator.py
- tests/test_integration.py
The equation for uncertainty evaluator ENCE is defined in an equation in Scalia et al.(2020). However, the equation implemented for ENCE in Chemprop neglects a square root operation on the variance, making it incorrect and not dimensionally consistent.
This PR corrects the bug and updates the testing values associated.
#356 Correctly identifies the bug in equation implementation and identifies what is needed for its correction.
> Correct a bug in ENCE uncertainty evaluation

- README.md
- chemprop/args.py
- chemprop/data/data.py
- chemprop/hyperopt_utils.py
- chemprop/hyperparameter_optimization.py
This PR addresses two problems in hyperparameter optimization.
One centers around a race condition where parallel instances read and write simultaneously to the file containing the list of previously used hyperopt seeds. Sometimes instances will coincide in their read/write timing and assign themselves the same seed and duplicate a trial. Currently, if an instance goes to save a trial and discovers that it already exists, it will raise an error because of the discovered conflict. This race condition is difficult to lock out in a way that will be effective for all operating systems. This PR doesn't solve the problem, but does reduce the severity of the discovery. Now, upon discovering that the saved trial already exists, an instance will note it in the log and continue on without raising …
> Hyperopt Parallel Race Conditions and Manual Trial Load

- .github/workflows/tests.yml
- README.md
- setup.cfg
- setup.py
The current install instructions require the user to separately install RDKit from the appropriate conda channel, and then install `descriptastorus` with `pip` separately before then installing `chemprop`. Now that [RDKit is on PyPI](https://pypi.org/project/rdkit-pypi/), the entire install can be consolidated into just `pip install chemprop` by adding the two dependencies to the `install_requires`.
Creating a fresh environment and running `pip install chemprop; pytest -v` passes all unit tests on my end.
This was all that added to `setup.py`:
```
'rdkit>=2020.03.1.0',
'descriptastorus @ git+https://github.com/bp-kelley/descriptastorus'
```
- README might need to be updated more than what I changed
~- [ ] (if appropriate) unit tests added?~
> Simplified install with PyPI `rdkit` and git install in `setup.py`

- README.md
- chemprop/args.py
- chemprop/data/data.py
- chemprop/sklearn_predict.py
- chemprop/sklearn_train.py
- tests/test_integration.py
In Chemprop, users cannot provide both loaded features and a features generator. This PR can allow users to use both loaded features and a features generator at the same time.
> Allow providing both loaded features and a features generator

- chemprop/uncertainty/uncertainty_estimator.py
Method `chemprop.train.make_predictions` assumes the ensemble individual predictions be of numpy array type. In case of multiclass tasks with enabled `--individual_ensemble_predictions` flag, it fails with `AttributeError: 'list' object has no attribute 'reshape'`. Please, find the MNWE below.
```python
from os import devnull
from chemprop.args import PredictArgs
from chemprop.train import load_model, make_predictions
CHECKPOINT_DIR = "/path/to/chemprop/model/dir"
predict_args = PredictArgs().parse_arg([
"--test_path", devnull,
"--preds_path", devnull,
"--checkpoint_dir", CHECKPOINT_DIR,
"--individual_ensemble_predictions"
])
(_, *rest_objects) = load_model(args=predict_args)
[[pred]] = make_predictions(args=predict_args,
smiles=["CCC"],
model_objects=(predict_args,) + …
```
> For any multiclass task, `make_predictions` fails if option --individual_ensemble_predictions is on.

- chemprop/utils.py
- tests/test_integration.py
Previously, the loaded molecular features can only be saved as `.csv` files when the `--save_smiles_splits` flag is used. However, if the molecular features are provided by `.npy` or `.npz` files, the `save_smiles_splits()` function would raise error. This BUG is described in #336.
In order to solve it, this commit supports saving molecular features in `.npy` files if not all the loaded molecular features are saved in `.csv` files.
> Save loaded molecular features into .npy files

- chemprop/rdkit.py
The new functionality of atom-mapped SMILES in rdkit.py may encounter an issue when the given SMILES is invalid.
The following is the error message displayed when an invalid SMILES is provided.
```
Traceback (most recent call last):
File "/home/gridsan/lmaeser/.conda/envs/chemprop/bin/chemprop_predict", line 33, in <module>
sys.exit(load_entry_point('chemprop', 'console_scripts', 'chemprop_predict')())
File "/home/gridsan/lmaeser/chemprop/chemprop/train/make_predictions.py", line 506, in chemprop_predict
make_predictions(args=PredictArgs().parse_args())
File "/home/gridsan/lmaeser/chemprop/chemprop/utils.py", line 591, in wrap
result = func(*args, **kwargs)
File "/home/gridsan/lmaeser/chemprop/chemprop/train/make_predictions.py", line 399, in make_predictions
full_data, test_data, …
```
> Ignore invalid atom-mapped SMILES

- chemprop/train/molecule_fingerprint.py
During the fingerprinting of molecules, invalid  SMILES will be ignored so there is no way to map the results back to the original SMILES list. This issue has been well described in #350.
Similarly to #235, a `return_invalid_smiles ` option is added to `molecule_fingerprint()`.
This `return_invalid_smiles` option indicates whether to include predictions for invalid datapoints, with the value "Invalid SMILES" in the function return. This makes it consistent with the saved value behavior. This option has been set default to True. The previous behavior before the option would have been False.
> Molecule fingerprinting with invalid SMILES in list

- chemprop/train/loss_functions.py
If the evidential parameter `v` gets too small, some values become Inf from division by `v`, ultimately causing a `ValueError`. Following the [practice](https://github.com/aamini/chemprop/blob/a7a137a09589474a5c5a83f75fbddbddfb877dc8/chemprop/utils.py#L160) used in the original evidential chemprop repo (for a different negative log likelihood function), we can use `torch.clamp` to make sure the value is always at least a certain minimum value (in this case, 1e-5).
Addresses #348
> Clamp evidential 'v' parameter

- chemprop/data/utils.py
To handle large fields in a .csv file, the field size was adjusted to `sys.maxsize`. The C long variable that holds this value varies in size depending on the operating system (OS) and CPU architecture. For instance, the long type size is typically 64 bits on Nix-like OS and 32 bits on Windows OS.
When setting the new value into `csv.field_size_limit()` function, it is necessary to ensure that it falls within the long boundaries. In some cases, an exception may occur, such as the `OverflowError: Python int too large to convert to C long` error encountered on Windows OS because `sys.maxsize` is typically 64-bit wide.
To avoid this problem, the maximum possible limit (LONG_MAX) can be set using the method described in this [link](https://stackoverflow.com/questions/15063936/csv-error-field-l …
> Avoid OverflowError when setting field size to sys.maxsize

- chemprop/args.py
The implementation of atom- and bond-level property prediction allows multitask constraints to be applied to different atomic/bond properties. The properties that are constrained are defined by the path to a .csv file specified by the `--constraints_path` flag. When using a checkpoint file for prediction, it will check which properties are constrained again from the file specified in the training argument of `--constraints_path`. This means that the checkpoint files cannot be used by other people. Since this information has already been stored in the checkpoint file, it is unnecessary to do that again.
In order to solve this bug, an attribute assignment is used to load the information of which properties are constrained from the checkpoint file instead of inferring from the original file …
> Set atom and bond constraints when loading model

- .gitignore
- pyproject.toml
- setup.py
This PR will be update both the package versions and the packaging system:
- `python >= 3.9` -> `python >= 3.11`
- `torch-1.X` -> `torch-2.X`
- `pytorch_lightning-1.X` -> `lightning-2.X`
- moving the packaging system from `setup.cfg` + `pyproject.toml` to solely `pyproject.toml`
> move packaging over

- .github/ISSUE_TEMPLATE/bug_report.md
We sometimes have people raise bug reports as issues with only the last line (or none) of the stack trace provided. We could add this to the template to encourage people to provide this if they're able, since this is often what we have to ask for in our first reply anyway.
> update bug report template - ask for full stack trace

- chemprop/sklearn_predict.py
- chemprop/train/make_predictions.py
- chemprop/train/molecule_fingerprint.py
- chemprop/utils.py
- scripts/find_similar_mols.py
The written csv files created by Chemprop include skipped lines when Chemprop is run on a Windows computer. This PR introduces a fix to avoid those skipped lines on Windows with no impact on Linux or Mac systems. The most common places this comes up are in the `test_scores.csv` output from training, the splits files generated in training when `--save_smiles_splits` is selected, and the predictions csv file generated during predictions jobs.
By adding `newline=""` into the with open block before csv writing, Windows systems will no longer write extraneous newlines in their csv files.
```
with open(args.evaluation_scores_path, "w", newline="") as f:
```
This should not affect Linux or Mac systems as the handling of newlines is carried out by the csv writer in each case.
This is not the only …
> Fixing skipped lines in csv writing when using a windows computer

- .github/workflows/tests.yml
Adds a new job the testing GitHub action that will automatically build and upload the Python package (which conda-forge should notice and upload within a day, auto-magically).
Currently a manual process, which is tedious.
This won't run except on pushes to main on this repository.
We will also need to generate a repo secret called `PYPI_API_TOKEN` which we can generate from pypi.org using the dev account.
- [] linted with flake8? (no python added)
> add job to tests action for PyPI package

- README.md
The ChemRxiv link to the Chemprop manuscript is now online, I have therefore added it to the README.
> added chemprop manuscript to readme

- chemprop/data/scaffold.py
- chemprop/features/featurization.py
- chemprop/rdkit.py
- tests/test_integration.py
PR #383 unexpectedly broke the atom mapping for reaction mode. The issue is described in Issue #426.
See Issue #426.
This PR changes the [`is_keeping_atom_map()`](https://github.com/chemprop/chemprop/blob/master/chemprop/features/featurization.py#L138) to always return `True` for reactions. In order to keep the scaffold splits running correctly,  the [`generate_scaffold()`](https://github.com/chemprop/chemprop/blob/master/chemprop/data/scaffold.py#L15) in scaffold.py is modified to remove atom mapping for the key molecule used for splitting before computing the Bemis-Murcko scaffold.
#426
> Fix reaction atom mapping

- chemprop/v2/data/datapoints.py
- chemprop/v2/models/hparams.py
- chemprop/v2/models/model.py
- chemprop/v2/models/modules/agg.py
- chemprop/v2/models/modules/message_passing/base.py
- chemprop/v2/models/modules/message_passing/molecule.py
- chemprop/v2/models/modules/readout.py
- chemprop/v2/models/schedulers.py
- chemprop/v2/models/utils.py
- example.py
The current object model utilizes composition to enable extensibility for future clients. However, this creates a problem for model checkpointing during training where the checkpoints are twice as large as necessary.
It is standard for `LightningModule`'s to call `save_hyperparameters()` at the top of their initializers, like so:
```python
class Model(LightningModule):
def __init__(self, in_feats: int, out_feats: int):
super().__init__()
self.save_hyperparameters
```
This call to `save_hyperparameters()` automatically saves both `in_feats` and `out_feats` to `self.hparams`, enabling seamless checkpoint loading for downstream applications. However, we run into problems when we create a model class which itself accepts other `nn.Module`s:
```python
class Model(LightningModule):
def …
```
> more efficient module checkpointing

- chemprop/v2/featurizers/atom.py
- chemprop/v2/featurizers/bond.py
- chemprop/v2/featurizers/reaction.py
This PR reworks the internals of the `AtomFeaturizer` to make it faster
Currently, the `AtomFeaturizer` class relies on a number of internal `Sequence`s which describe the possible choices for each subfeature in an overall atomic feature vector. During atom featurization, an atom would have some descriptors calculated and the index of the descriptor would be retrieved from the list of respective subfeature choices. I.e.,
```python
atomic_nums = range(100)
a: Chem.Atom
n = a.GetAtomicNum() - 1
i = atomic_nums.index(n) if n in atomic_nums else len(atomic_nums)
```
However, retrieving the index of an item in a sequence is O(N), so atom featurization can end up being fairly "slow"
Given that the main work for atom featurization is essentially index retrieval, the internals of the …
> improve the `AtomFeaturizer`

- chemprop/v2/cli/predict.py
- chemprop/v2/cli/train.py
It is preferable to keep the CLI for v2 compatible with existing workflows for v1, where possible. This PR adds arguments from v1 to v2 that were missing previously. Additionally this PR changes some argument names from using dashed "-" to underscores "_" to match the style of v1. Some arguments were given different names in v2 compared to v1. The v2 new names were preserved and the v1 name was given as an option. See examples below. 
Use of the RegistryAction() class was also fixed. 
`parser.add_argument("-o", "--output-dir")`
was changed to
`parser.add_argument(
"-o", 
"--output-dir",
"--preds_path",
type=str,
help="Path to CSV or PICKLE file where predictions will be saved.",
)`
The option to show individual scores was available in v1 and is now added to v2
`train_args.add_argument( …
> Adding train and predict args from v1 to v2, for backward compatibility

- chemprop/args.py
- chemprop/data/data.py
- chemprop/data/utils.py
- tests/test_unit/test_data_utils.py
Added another way to split the data based on the molecular weight. By default small molecules go to the train subset and larger to the subset. This provides a more challenging split for the generalization of the moelecules. Several datasets are biased towards small molecules so by using this split the user can assess the generalizability of the model better before applying external datasets.
Same call:
chemprop_train --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints --split_type scaffold_balanced --save_smiles_splits  
The output files prove the correctness of the split.
[test_smiles.csv](https://github.com/chemprop/chemprop/files/12619953/test_smiles.csv)
[val_smiles.csv](https://github.com/chemprop/chemprop/files/12619954/val_smiles.csv) …
> new split per molecular weight

- chemprop/v2/data/datasets.py
- chemprop/v2/featurizers/__init__.py
- chemprop/v2/featurizers/reaction.py
- chemprop/v2/tests/unit/featurizers/test_atom.py
- chemprop/v2/tests/unit/featurizers/test_bond.py
- chemprop/v2/tests/unit/featurizers/test_molgraph.py
The tests for the atom, bond, and molgraph featurizers have been updated to pass in v2. RxnMolGraphFeaturizer has been renamed to CGRFeaturizer. A placeholder test_cgr.py has been added to the featurizers unit test folder. 
1. In test_atom.py, number of subfeatures has been changed to match new featurization, and the indices in the atom featurers vector have been modified to ensure checking of aromaticity and atomic mass. 
2. In test_bond.py, the one_hot_index function is used to check that the bond type and conjugation properties are set in the right index in the bond feature vector. 
3. In test_molgraph.py, a missing not was added to ensure that the bond_message argument is being set correctly during the unit test. The passing of additional atom and bond features for the unit test has …
> V2 atom, bond, and molgraph featurizers unit tests

- chemprop/v2/cli/train.py
As discussed at length internally, we are taking the major version bump as an opportunity to change several default settings:
* epochs: 30 --> 50
* aggregation: mean --> norm
* batch_size: 50 --> 64 (already done by #485)
* HPO search space (to be implemented later, see #496)
Based on years of experience training chemprop models across many people in the group, we believe that these defaults are more likely to lead to better models in many cases. These can obviously be problem-dependent, though, so they can and should still be varied depending the problem and empirical results.
Are there any other places in the code these defaults need to be changed, other than in the CLI?
> v2: update CLI defaults for epochs and aggregation

- chemprop/v2/models/loss.py
- chemprop/v2/models/metrics.py
- chemprop/v2/tests/unit/test_loss_functions.py
This PR adds a unit test for the loss functions defined in `loss.py`. The tests are not exhaustive, but include a test for each loss function available and check for basic functionality such as expected dimensions, reduction, and simple parameters. Some loss function definitions in `loss.py` are modified to address some issues. These are: 
1) BoundedMSELoss is modified to have the lt and gt masks applied to the targets in addition to preds. 
2) MulticlassMCCLoss is modified to have summations such that the end vector is a scalar. This should match the implementation in v1. 
3) BinaryDirichletLoss and MulticlassDirichletLoss have had their forward call modified to pass to DirichletMixin as the loss was previously returning a NoneType.  
`metrics.py` has also been updated to have metrics …
> Add v2 unit test for loss functions and update loss/metrics

- LICENSE.txt
This pull request updates the copyright line of the MIT license file to be the current year and add many of the major contributors from the intervening time. This was discussed with Bill. Now that the list is long and extends beyond one paper, I have also moved to alphabetically sorting the names.
> Update authors list in license file and alphabetically sort

- chemprop/v2/data/__init__.py
- chemprop/v2/data/splitting.py
- chemprop/v2/tests/unit/data/test_data_utils.py
Texts below are copied from https://github.com/chemprop/chemprop/pull/500#issuecomment-1771956143.
During working on an example notebook for multicomponent training, there are several things I noticed that the split_data is currently awkward and can be improved for multi-components.
With https://github.com/chemprop/chemprop/pull/501, a MulticomponentDataset dataset contains K datasets where K is the number of components. These K datasets need to be split consistently. The current split_data function is not able to do that. I discussed this with @KnathanM and we thought of some ways to do this, and I implemented one of them. Here are the possible options we came up with:
Option 1: Generalize split_data to be able to take in K lists of datapoints, use one of them to do the splitting, apply …
> V2: Improve datasplit function for multicomponent dataset

- LICENSE.txt
- setup.cfg
- setup.py
I realized a couple things after merging #532:
* there are also authors lists in the `setup.py` and `setup.cfg` files that should probably also be updated to match the new list in the `LICENSE.txt`
* we left out a couple people in #532: Lior Hirschfeld and Yanfei Guan (who are both relatively high on the [contributors list](https://github.com/chemprop/chemprop/graphs/contributors)), and Allison Tam (who does not show up under GitHub contributions, but was listed in the `setup.py` and `setup.cfg` files)
Note that these new author lists do not include several people who have made significant contributions to the v2 code. They will be added in a future PR related to #489
> update authors in LICENSE and setup files for v1

- .github/workflows/tests.yml
Addressed questions regarding testing example notebooks raised in https://github.com/chemprop/chemprop/issues/559. Building on top of and should be merged after https://github.com/chemprop/chemprop/pull/560. Attempting to run example notebooks using pytest plugin https://github.com/treebeardtech/nbmake in GitHub Action.
> V2: run example notebooks in GitHub Actions

- chemprop/cli/common.py
- chemprop/cli/train.py
This PR just connects the splitting args to the code. It also comments out the splitting args that aren't ready yet. 
It also fixes a bug in common.py (`choices=RxnMode.keys(),`). Discussed in #497.'
Note: Support for splitting by molecular weight was added recently to v1, but has not been added to v2.
Support for premade data splits could be added to this PR as well as support for saving smiles splits. These seemed more complicated so were left for later. One question is if they should be added to this PR instead.
Another question is if 'crossval' and 'cv' are the same splitting method. In v2 they show up as two options, which confused me because I thought 'cv' stood for 'crossval'. Currently 'crossval' isn't an option from the commandline.
> V2: Args for data splitting

- chemprop/features/features_generators.py
#435 describes a bug where `descriptastorus` complains that `scipy.stats` doesn't have the attribute `gilbrat`. This was fixed in the latest version of `descriptastorus`, but the error message doesn't indicate that is the problem. This PR makes the error message more helpful. 
Fixes #435
Closes #436
> Improve error message when gilbrat is needed.

- chemprop/nn/message_passing/multi.py
- tests/integration/conftest.py
- tests/integration/test_regression_multimol.py
This PR will close https://github.com/chemprop/chemprop/issues/575 by adding an integration test for mol+mol regression.
[If appropriate, please tag them here and include a quick summary](https://github.com/chemprop/chemprop/issues/575)
> V2: add integration test for mol+mol regression

- chemprop/nn/predictors.py
Following from https://github.com/chemprop/chemprop/issues/615 , this PR fixes the Attribute error that currently throws when trying to create a SpectralFNN class.
> Fixing SpectralFNN self.fnn.fnn issue

- environment.yml
- setup.cfg
- setup.py
I have tested that both the conda environment can be built and the package can be installed using `conda create -n test_cprop -f environment.yml --dry-run` and `pip install . --dry-run` (from the chemprop dir).
This PR would close #565 if merged (see issue for more detail).
For clarity, I have removed the "Python 3" label from the setup scripts, emphasizing we don't support arbitrary versions of Python 3.
> limit chempropv1 python version to 3.7, 3.8 only

- chemprop/cli/predict.py
- chemprop/models/model.py
- chemprop/nn/message_passing/proto.py
- tests/cli/test_cli_regression_mol+mol.py
- tests/cli/test_cli_regression_mol.py
- tests/integration/test_regression_mol.py
- tests/integration/test_regression_multimol.py
This PR addresses https://github.com/chemprop/chemprop/issues/590. I added pytest for the CLI functionality. 
- Currently the test only tests that the CLI can run and use only 1 epoch. Should we increase the epoch and test the model performance? For example, we can pass the model generated by the training CLI test, and load it using the predicting CLI, and test the errors. I don't think it's necessary as this test focuses on the CLI connection aspect, and the model performance is tested by the integration test. But I want to know people's thoughts.
This PR addresses https://github.com/chemprop/chemprop/issues/590.
> V2: Add pytest for CLI functionality

- CITATIONS.bib
GitHub has a nice UI button to automatically cite a repo using a preferred citation, this just adds the necessary file to make it pop up.
Note that the original issue requested adding a `CITATION.cff` file, but this PR adds a `CITATIONS.bib` file instead. This is because we want to include multiple citations, and the former format does not support that use case (but the latter does).
I have only included the two 'main' chemprop papers in the citations file, following some discussion with @kevingreenman. We considered adding others, but because these are the only two that are _required for all use of chemprop_, we decided against adding other feature-specific citations (which could be seen as citation farming).
Closes #394. 
When v2 is eventually merged (or just changed to the default …
> Add a `CITATIONS.bib`

- environment.yml
- setup.cfg
- setup.py
#437 first reported that with versions of `flask` greater than 2.1.3, the Chemprop website running locally would break. PR #438 fixed this, but introduced backwards incompatible changes with previous versions of flask.
In the spirit of closing all of our v1 issues before v2, this PR simply caps the maximum allowed version of `flask` to one which supports the syntax used in Chemprop, rather than attempting to fix the syntax as done in #438. This isn't a better solution, but is less work for the (busy) maintainers.
Closes #437. Supersedes #438.
> Limit Maximum Allowed `flask` Version in v1

- chemprop/train/make_predictions.py
As described in #603, the `num_unc_tasks` is sometimes referenced before assignment `if not save_results` and `if return_invalid_smiles`. Moving it outside of the `if save_results:` block should resolve this problem.
Fixes #603
> move num_unc_tasks definition to ensure always defined

- chemprop/args.py
- chemprop/train/cross_validate.py
- chemprop/train/run_training.py
- chemprop/utils.py
Currently, multitask metrics are computed in the `multitask_mean` function by taking the mean metric across all tasks. 
https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/utils.py#L868
However, this means that if there is even a single task with a NaN metric (e.g., if one task has a test split with all 0s or all 1s for the AUC metric), then the mean metric will also be NaN.
For example, this occurs when training on the ToxCast dataset, which has some imbalanced tasks that have all 0s or all 1s in some test splits.
```
python train.py --data_path data/toxcast.csv --dataset_type classification --epochs 1 --quiet
```
Running the above command produces the following output:
```
Ensemble test auc = nan
1-fold cross validation
Seed 0 ==> test auc = nan …
```
> Switching np.mean to np.nanmean to handle NaN metrics

- chemprop/cli/train.py
- tests/cli/test_cli_regression_mol+mol.py
- tests/cli/test_cli_regression_mol.py
This arises during implementing the CLI tests in https://github.com/chemprop/chemprop/pull/602.
- I save the Namespace object as a dictionary to a .json file at path `args.output_dir / "config.json"`
- I save the smiles splits for train, val, and test at paths `args.output_dir / "train_smiles.csv"`, `args.output_dir / "val_smiles.csv"`, and `args.output_dir / "test_smiles.csv"`.
> V2: save command config and smiles splits

- chemprop/cli/train.py
Very simple PR to implement `--grad-clip`.
V1 had this option. This is a step towards feature parity. 
In v1 this is simply [passed](https://github.com/chemprop/chemprop/blob/d58d877fd1d652929b0216e7b0cc11355664fd97/chemprop/train/train.py#L221) to `torch.nn.utils.clip_grad_norm_()` with all model parameters. Lightning [says](https://lightning.ai/docs/pytorch/stable/advanced/training_tricks.html#gradient-clipping) it does the same thing through the `gradient_clip_val` argument to `Trainer`. `None` is the [default](https://lightning.ai/docs/pytorch/stable/_modules/lightning/pytorch/trainer/trainer.html) which disables gradient clipping. `None` is also the value of `args.grad_clip` if the user doesn't specify it. 
I welcome suggestions on the help string for `--grad-clip`.
> V2: add grad clip

- .readthedocs.yml
This PR changes the v1 Read the Docs (RTD) yml file to use mamba instead of conda to build the documentation. In preparation for the v2 release (which will have a new set of RTD documentation) I would like to have the v1 RTD working again so that the note I added to our RTD homepage in [this commit](https://github.com/chemprop/chemprop/commit/386d480553e493577b050d7c47f51aba3e0ac6dc) will show up if someone is still using v1.x and tries to look at the old documentation. We regularly get people asking questions in issues/discussions because they haven't looked at the README and assume that our RTD is up-to-date for v1.x (which is not an unreasonable assumption, IMO).
Our v1 documentation has been failing to build since October 2022, sometimes due to excessive memory consumption (e.g. see …
> switch v1 readthedocs build from conda to mamba

- LICENSE.txt
- README.md
- docs/source/conf.py
- docs/source/index.rst
- environment.yml
- setup.cfg
- setup.py
The v1 docs are successfully building again, but their theme looks very different from what it did before. The theme was previously set to `default`, but it displayed as if the theme was `sphinx_rtd_theme`. This PR makes the `sphinx_rtd_theme` explicit so the docs look like they did before (which I think looks much nicer than the default). 
Some pages (e.g. [here](https://chemprop.readthedocs.io/en/latest/args.html)) are also formatted poorly using the default theme. The new theme fixes that.
Additionally, I made the note I added in #660 into warning using the "admonition" format so it will stand out from the other paragraphs on the page and be more noticeable. 
[Build status](https://readthedocs.org/projects/chemprop/builds/23545535/) - succeeded
[Preview of new version of …
> Fix v1 docs theme

- chemprop/data/dataloader.py
Calling `nn.BatchNorm1d` on a batch of size 1 will lead to a ValueError. This can occur if the remainder of the dataset and the batch size is 1 (for example, dataset has 101 samples and the batch size is 10). 
From a clean install of Chemprop, install the FreeSolv dataset and run the command:
`chemprop train --data-path data/freesolv.csv --task-type regression --output-dir freesolv`
which will lead to a ValueError. Traceback shows that this is due to calling `batch_norm` for a batch of size 1.
This PR implements one fix suggested in https://github.com/pytorch/pytorch/issues/4534, which is to drop the last batch if its size is 1. This also includes a warning so that the user can see that this happened.
do we expect any problems with using `len(dataset)` for `MulticomponentDataset` and …
> V2: Modify DataLoader to drop last batch if its size is 1, to avoid batch norm issues

- chemprop/data/collate.py
- tests/unit/data/test_dataloader.py
This problem was found during https://github.com/chemprop/chemprop/pull/635, where I encountered dimension issue when trying to add tests for atom descriptors. I found that the `collate` for `V_d` is incorrect.
Currently, `collate` stack `V_d`. However, the dimension of `V_d` should be number of atoms by number of atom descriptors. Due to the different number of atoms, we're not able to stack them. Instead, they should be concatenated. A sanity check on this is that the `V` from batch mol graph should contain the same number of atoms as the `V_d`.
The V and V_d in each datum should have the same number of atoms, but the current test case in the dataloader test doesn't.
I change `stack` to concatenate and update the test to check that number of atoms in `V` and `V_ds` match. I also update …
> V2: Debug V_d in collate and dataloader test

- README.md
SSL+DDP was not merged into `master` Chemprop, but we need to let people know how to get it.
> add note on feature releases and instructions for ssl+ddp

- chemprop/multitask_utils.py
- chemprop/train/make_predictions.py
- chemprop/uncertainty/uncertainty_calibrator.py
- chemprop/uncertainty/uncertainty_predictor.py
The `num_tasks` argument of the reshape functions can actually be calculated as the summation of `natom_targets` and `nbond_targets`.
> remove unnecessary argument for reshape function

- chemprop/cli/train.py
- chemprop/models/model.py
- tests/cli/test_cli_regression_mol.py
While working on saving the predictions for multitask MVE model, I have found errors in single-task MVE model. This PR aims to iron out the bugs and adds tests.
Current workflow passes the preds to metric for evaluation directly. For MVE regression, the preds contain both the mean and the var, so this fails with dimension mismatch error.
```
def _evaluate_batch(self, batch) -> list[Tensor]:
bmg, V_d, X_f, targets, _, lt_mask, gt_mask = batch
mask = targets.isfinite()
targets = targets.nan_to_num(nan=0.0)
preds = self(bmg, V_d, X_f)
return [
metric(preds, targets, mask, None, None, lt_mask, gt_mask)
for metric in self.metrics[:-1]
]
```
I added an if block to check if the predictor is an `MveFFN` and takes the mean portion of the preds. Happy to take suggestions on a more elegant to to …
> V2: Fixing MVE regression and adding tests

- chemprop/cli/train.py
Fixes the usage of the `seed` and `pytorch-seed` CLI arguments, the latter of which was not used at all.
I've renamed `seed` to `data-seed` to better reflect its purpose. This argument was already used for data splitting, but I've now added it to the train dataloader as well. `shuffle` will still be `True` by default for the train dataloader (and `False` for the val and test dataloaders), but users who run the same training job multiple times without specifying the seed will now get reproducible results. This is how we did it in v1.
* Should `seed` be `None` by default in `MolGraphDataLoader`? That's what we have now. If we're going to have the seed for the train dataloader be 0 by default when using the CLI (matching v1), should we also update this default to 0?
> V2: use seed and pytorch_seed appropriately

- chemprop/interpret.py
Fixes #689 
As mentioned there, this argument is not passed to `MoleculeDataLoader` during interpretation [here](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/interpret.py#L59), whereas it is passed to `MoleculeDataLoader` during [training](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/run_training.py#L238), [prediction](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/make_predictions.py#L92), and [fingerprinting](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/molecule_fingerprint.py#L87).
> Pass num_workers to MoleculeDataLoader during interpretation

- chemprop/nn/agg.py
- tests/integration/conftest.py
- tests/integration/test_regression_mol.py
- tests/integration/test_regression_rxn.py
https://github.com/chemprop/chemprop/issues/705 ran into error when using the norm aggregation. Currently we only test sum aggregation in the integration test. I add tests for other aggregation methods.
The error is from the forward function of norm aggregation. An extra `self.dim` is passed in, which is not necessary.
```
@AggregationRegistry.register("norm")
class NormAggregation(SumAggregation):
r"""Sum the graph-level representation and divide by a normalization constant:
.. math::
\mathbf h = \frac{1}{c} \sum_{v \in V} \mathbf h_v
"""
def __init__(self, dim: int = 0, *args, norm: float = 100, **kwargs):
super().__init__(dim, **kwargs)
self.norm = norm
self.hparams["norm"] = norm
def forward(self, H: Tensor, batch: Tensor) -> Tensor:
return super().forward(H, batch, self.dim) / …
```
> V2: Debug and add tests for various aggregation methods

- chemprop/uncertainty/uncertainty_predictor.py
The shape of `uncal_vars` should be the same as that of `sum_preds`.
> fix the `uncal_vars` for atom/bond property prediction

- .github/workflows/tests.yml
- README.md
Replaces #715 - official Chemprop Docker images will now be available at DockerHub.
Current readme only describes how to build locally.
I have pushed the latest tag to DockerHub and will start working backwards building and pushing some previous versions as well.
In the future, the added action will automatically build images based on `master`, and we can manually tag them with release numbers as we do formal releases.
> [v1]: Add Docker Image Building Action and Official Images to DockerHub

- .github/workflows/tests.yml
Removes macos from CI for v1, removes unused windows logic.
Currently the MacOS builds hangs forever (probably due to a memory issue with github actions) and there are old windows lines that no longer apply. The former prevents the pypi/docker builds from running, since they both depend on the tests passing (which macos doesn't).
Just remove MacOS. We are sunsetting v1, so this is just to push it over the finish line rather than fix it.
> remove macos and windows from v1 ci

- .github/workflows/tests.yml
`main` -> `master`
Just copied this wrong from the original and had the wrong default branch name.
> update docker build `if` to use correct upstream branch name

- Dockerfile
- docs/source/installation.rst
- note that this is locked on a specific version of pytorch, pytorch scatter, and chemprop (down to the commit hash)
- this only runs on CPU, but includes some minimal instructions to help people get going on GPU
- tested locally by building, running, and then training a quick FreeSolv model without issue
I have also generally overhauled the Dockerfile based on how we distribute RMG-Py via Docker, see [that Dockerfile](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/Dockerfile), which has been working without issues for a while now.
> revise dockerfile for chempropv2

- chemprop/train/run_training.py
The `args.task_names` unexpectedly changed to `args.task_names` in PR #693. 
When `--save_preds` is used, it would lead to below error:
```
for i, task_name in enumerate(task_names):
UnboundLocalError: local variable 'task_names' referenced before assignment
```
> fix the task names

- chemprop/models/model.py
- chemprop/models/multi.py
This PR fixes an interesting error with our use of `save_hyperparameters()` that prevents loading checkpoint files in python 3.12. We have had discussion of this several places (#714 and #738). I learned a lot while debugging this and felt it was too long for a comment. So I opened this PR both to isolate the change to demonstraight it works and also to have the space to explain what is going on. I'd be also happy to include this change in the other PR and close this one. 
When we call `save_hyperparameters()` in the `__init__` of our modules (e.g. `_MessagePassingBase`) lightning will "Recursively collects the arguments passed to the child constructors in the inheritance tree." It knows when to stop by looking for the absense of `__class__` in the local variables. It can do this because …
> Fix load from checkpoint in python 3.12

- chemprop/data/datapoints.py
- chemprop/nn/agg.py
- chemprop/nn/message_passing/base.py
- chemprop/nn/predictors.py
This tiny PR addresses #686 and tidies up initialization of some previous arguments that are meant to be floats but were initialized as ints. Specifically, weight in `_DatapointMixin`, norm in `NormAggregation`, and dropout in both `predictor.py` and `base.py` had their default values updated to be floats. 
#686
> Tidy up float parameter default values

- chemprop/cli/train.py
- chemprop/cli/utils/parsing.py
- chemprop/data/collate.py
- chemprop/featurizers/molgraph/molecule.py
MPS framework doesn't support float64. Some attributes in a datapoint are saved as float64. Converting them to float32 can solve this issue.
#711
> V2: Convert from float64 to float32

- chemprop/data/datasets.py
@am2145 found that the reaction prediction gives unreasonable values during benchmarking. We reduce the problem down to something is wrong with the scaler. However, it doesn't affect the molecule prediction. We eventually found that it is because `__getitem__` is pulling the wrong values for reaction dataset.
n/a
We should get the inputs and the targets from the dataset, but not the datapoint raw values for training.
n/a
n/a
> V2: Fix reaction scaling

- chemprop/cli/train.py
- chemprop/cli/utils/parsing.py
- tests/cli/test_cli_regression_mol.py
I introduced a bug where having a splits column wasn't accounted for in get column names. I also saw it was missing the weights column so added that. And generally tried to make the code more concise. Note that if there is no header row, it doesn't make sense to use any of the column CLI args (--smiles-columns, etc.) because there are no headers to reference.
> clean up column names

- chemprop/cli/hpopt.py
Currently, the training and validation dataloaders are generated once and used for all the trials in HPO. Therefore, the same dataloaders are passed to `trainer.fit()` multiple times. This should be avoided, as the same dataloader will be sampled differently during different trials. Moreover, it could also cause the #808 test to fail because the index in the sampler (see [here](https://github.com/chemprop/chemprop/blob/v2/dev/chemprop/data/samplers.py#L19-L23)) will become a read-only object and cannot be shuffled again for the following trials.
> Generate dataloader for each trial

- chemprop/cli/fingerprint.py
- chemprop/cli/hpopt.py
- chemprop/cli/predict.py
- chemprop/cli/train.py
- chemprop/data/__init__.py
- chemprop/data/dataloader.py
- docs/source/tutorial/python/index.rst
- examples/mpnn_fingerprints.ipynb
- examples/predicting.ipynb
- examples/predicting_regression_multicomponent.ipynb
- examples/predicting_regression_reaction.ipynb
- examples/training.ipynb
- examples/training_regression_multicomponent.ipynb
- examples/training_regression_reaction.ipynb
- tests/unit/utils/test_converter.py
Currently `trainer.predict` uses a batch size of 1 when given a `MolGraphDataLoader`. Simple code to reproduce:
```
from lightning import pytorch as pl
from chemprop import nn
from chemprop.models import MPNN
mp = nn.BondMessagePassing()
agg = nn.MeanAggregation()
ffn = nn.RegressionFFN()
mpnn = MPNN(mp, agg, ffn)
trainer = pl.Trainer()
import torch
from chemprop.data import MoleculeDatapoint, MoleculeDataset, MolGraphDataLoader
from chemprop.featurizers import SimpleMoleculeMolGraphFeaturizer
fake_data = [MoleculeDatapoint.from_smi('C', torch.tensor([1])), MoleculeDatapoint.from_smi('C', torch.tensor([2]))]
featurizer = SimpleMoleculeMolGraphFeaturizer()
fake_dset = MoleculeDataset(fake_data, featurizer)
fake_loader = MolGraphDataLoader(fake_dset, shuffle=False)
trainer.test(mpnn, …
```
> Pass kwargs through to DataLoader in MolGraphDataLoader

- chemprop/data/dataloader.py
We changed the default batch size in the CLI to 64 [here](https://github.com/chemprop/chemprop/blob/4bba6776e248fc4440a3c279aeb790d252fce818/chemprop/cli/common.py#L41), but we didn't change it in dataloaders.py
> fix dataloader batch size

- chemprop/cli/train.py
- chemprop/models/model.py
- chemprop/nn/loss.py
- chemprop/nn/metrics.py
- chemprop/utils/v1_to_v2.py
In #779 we moved task weights to be an attribute of LossFunction. This means it is also an attribute of Metric even though it isn't used. We will address this more thoroughly in v2.1, but requiring task weights when creating a metric will be confusing for users. I thought about it some more and feel task weight should also not be required for when making a loss function if all task weights should be one.
Before I didn't put default task weights of ones in the init for LossFunction because in the LossFunction we don't know how many tasks there will be. Compare to predictors.py that uses `torch.ones(n_tasks) to make a default task weights. But then I realized if we want all ones, we don't have to have the length right because it can be broadcasted. 
This PR allows for simple creation of …
> Add default task weights 

- pyproject.toml
@shihchengli identified in #825 that the reason our readthedocs build is failing is due to a change in `docutils`, which is a dependency of `sphinx`. Restricting the version to below 0.21 should fix this issue.
> v2: restrict docutils to version < 0.21

- Dockerfile
- docs/source/installation.rst
- added instructions for `environment.yml`
- updated docker instructions to remove references to release candidate (fixes #827)
- updated PyPI instructions to remove `--pre` flag
- minor reorganization
> update v2 installation instructions page in docs

- docs/source/installation.rst
The installation instructions for installing with conda environment.yml was missing a step in setting up the cli command support. This PR adds the `pip install -e .` step to the installation.
> Add pip setup step to environment.yml install instructions

- chemprop/cli/utils/parsing.py
Partially addresses https://github.com/chemprop/chemprop/issues/890
All this does is remove use of `set` to avoid scrambling order of target columns.
> Avoid scrambling target column name order

- chemprop/cli/hpopt.py
We currently use [AsyncHyperBand](https://docs.ray.io/en/latest/tune/api/schedulers.html) as the only trial scheduler. In v1, we ran HPO without discarding any trials during the process, which is what FIFO scheduler in Ray does. This PR changes the default to FIFO and adds an argument `--raytune-trial-scheduler` to allow using `AsyncHyperBand` if needed.
> Change the default trial scheduler to `FIFOScheduler`

- chemprop/cli/utils/actions.py
We use [ConfigArgParse](https://pypi.org/project/ConfigArgParse/) to have easy config file support. But when we try to use our `LookupAction` and `nargs='+'` we have an error.
`chemprop train --config-path config.toml`
```
$ cat config.toml
data-path = tests/data/classification/mol.csv
metrics = [mse, rmse]
features-generators = [morgan_count, morgan_binary]
```
```
usage: chemprop train [-h] [--logfile [LOGFILE]] [-v] [-s SMILES_COLUMNS [SMILES_COLUMNS ...]]
[-r REACTION_COLUMNS [REACTION_COLUMNS ...]] [--no-header-row] [-n NUM_WORKERS] [-b BATCH_SIZE]
...
[--pytorch-seed PYTORCH_SEED]
chemprop train: error: metrics can't be set to a list '['mae', 'rmse']' unless its action type is changed to 'append' or nargs is set to '*', '+', or > 1
```
LookupAction does two things:
1. enforce the …
> make LookupAction work with ConfigArgParse

- chemprop/cli/train.py
We want to have caching in the CLI as it speeds up training. I decided to always have caching on as the default with the option to turn it off. This is because in my tests with 1 M datapoints, the cached Molgraphs only took on the order of 10 GB of memory. I figure if someone is trying to train on 1M datapoints, they probably have that much memory to spare. 
I don't cache the test set as it is only used once so the MolGraphs only need to be calculated once and caching doesn't help with that. 
My tests:
```
from rdkit import Chem
from chemprop import data
mol = Chem.MolFromSmiles("CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C") # Penicillin
datapoints = [data.MoleculeDatapoint(mol) for _ in range(1_000_000)]
dataset = data.MoleculeDataset(datapoints)
dataset.cache = True
```
I found …
> Add simple cache to CLI

- docs/source/index.rst
- docs/source/tutorial/cli/index.rst
We have a CLI transition guide spreadsheet for v2 that we've linked in the README and release notes, but this should also be added to the Read the Docs for better visibility.
> Add CLI transition guide link to RTD

- chemprop/cli/hpopt.py
Currently, if a user uses `epoch <= 6` to test hyperparameter optimization that includes warm up epoch, it would fail with the following error message that is not easy to understand. I added a meaning error message.
```
Traceback (most recent call last):
File "/home/hwpang/miniforge3/envs/chemprop_v2_dev/bin/chemprop", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/hwpang/Projects/chemprop_v2_dev/chemprop/chemprop/cli/main.py", line 80, in main
func(args)
File "/home/hwpang/Projects/chemprop_v2_dev/chemprop/chemprop/cli/hpopt.py", line 107, in func
main(args)
File "/home/hwpang/Projects/chemprop_v2_dev/chemprop/chemprop/cli/hpopt.py", line 430, in main
results = tune_model(
^^^^^^^^^^^
File "/home/hwpang/Projects/chemprop_v2_dev/chemprop/chemprop/cli/hpopt.py", line 377, in …
```
> Add meaningful warming for warm up epoch search space

- chemprop/cli/hpopt.py
…r (instead of default)
Addresses #912 
Currently, default max-lr used to calculate the init-lr and final-lr (from init-lr-ratio and final-lr-ratio). This is for the outputs in the best_cnfig.toml file.
Change the default value to the best value found using hpopt.
#912
> Fixing small bug in hpopt for learning rate

- pyproject.toml
Scheduled CI run failed today (see [here](https://github.com/chemprop/chemprop/actions/runs/9544345920)). Thanks to @JacksonBurns for finding the reason. It is because NumPy just released v2, and RDKit doesn't support it yet. By changing the installed version in pyproject.toml to v1, the issue is resolved. When the other dependencies support NumPy v2, we can add it back then.
> Change the installed numpy version in pyproject

- chemprop/cli/train.py
- tests/cli/test_cli_classification_mol.py
- tests/cli/test_cli_classification_mol_multiclass.py
- tests/cli/test_cli_regression_mol+mol.py
- tests/cli/test_cli_regression_mol.py
- tests/cli/test_cli_regression_mol_multitask.py
- tests/cli/test_cli_regression_rxn+mol.py
- tests/cli/test_cli_regression_rxn.py
Add `--show-individual-scores` so all scores for individual targets will be shown.
Run this CLI
```
chemprop train \
-i data/regression/mol/mol.csv \
--epochs 1 \
--task-type regression \
--ensemble-size 2 \
--show-individual-scores
```
You will see individual scores for each target after each model training is finished.
```
INFO:__main__:Entire Test Set results:
INFO:__main__:entire_test/mse: 1.035393409031115
INFO:__main__:Entire Test Set individual results:
INFO:__main__:entire_test/lipo/mse: 1.035393409031115
```
#719
> Add `--show-individual-scores` CLI flag

- chemprop/cli/hpopt.py
See ray's [documentation](https://docs.ray.io/en/latest/train/user-guides/using-gpus.html#trainer-resources) for details.
> This object often only manages lightweight communication between the training workers. You can still specify its resources, which can be useful if you implemented your own Trainer that does heavier processing.
> Per default, a trainer uses 1 CPU. If you have a cluster with 8 CPUs and want to start 4 training workers a 2 CPUs, this will not work, as the total number of required CPUs will be 9 (4 * 2 + 1). In that case, you can specify the trainer resources to use 0 CPUs:
Since Ray Train's Trainer only handles lightweight communication per the documentation, we can specify its resources to be 0 cpu.
> Set Ray Train's trainer resources to 0

- chemprop/cli/fingerprint.py
- chemprop/cli/predict.py
- tests/cli/test_cli_classification_mol.py
- tests/cli/test_cli_classification_mol_multiclass.py
- tests/cli/test_cli_regression_mol.py
The predictions of each model in a directory are currently saved as separate files and are not automatically averaged. This PR puts the average results into a single file. In the case of ensemble models, the individual predictions for each file will be saved into another file with the file name ending in `_individual.csv` or `_individual.pkl`. The column name would be `{target_name}_model_{ind}`. For example, if you train a model on target U0 with two ensembles, the column names would be U0_model_0 and U0_model_1. In addition to saving predictions to two files, this PR also changes the previous behavior of loading the test dataset for each model to only loading it once and using this dataloader for all the models.
As mentioned in #890, the current target names are not saved in the model …
> Save individual and average predictions into different files

- chemprop/cli/fingerprint.py
- chemprop/cli/predict.py
Recently we have merged in https://github.com/chemprop/chemprop/pull/731, which changes the behavior of `--model-path` in predict.py to be the following
- It can take multiple locations of model (.pt) files and (.ckpt) checkpoints
- If a directory is given, search for all (.pt) models using the `find_models` helper function
The fingerprint.py has a same argument `--model-path` and a duplicate `find_models` helper function.
Instead of maintaining two functions doing the same thing, I move the `find_models` helper function into common.py. Both predict and fingerprint now use the same helper function code.
I change the `--model-path` in fingerprint.py to behave the same as predict.py, and change the help string to reflect the new behavior.
I also added the index corresponding to the model …
> Make fingerprint CLI consistent with predict CLI

- chemprop/cli/fingerprint.py
https://github.com/chemprop/chemprop/issues/894 found a bug related to target column in inference, and https://github.com/chemprop/chemprop/pull/895 applied a fix to it. The same bug can occur to fingerprinting, so I apply the same fix to `chemprop fingerprint`.
> Fix issue related to target column for fingerprint

- chemprop/cli/train.py
In the v1 to v2 [transition guide](https://docs.google.com/spreadsheets/u/3/d/e/2PACX-1vRshySIknVBBsTs5P18jL4WeqisxDAnDE5VRnzxqYEhYrMe4GLS17w5KeKPw9sged6TmmPZ4eEZSTIy/pubhtml#), we note that the default aggregation type was changed from mean to norm. But looks like we didn't actually make that change...
I don't think there will be any side affects to changing this default. Previous model files will have "mean" saved as a hyperparameter. All of our benchmarking scripts already specify `--aggregation norm`.
> change aggregation default to norm

- chemprop/nn/loss.py
The default value `task_weights` of `LossFunction` was set to `1.0` in #821, but some loss functions were not changed accordingly.
> Standardize `task_weights` in `LossFunction` across all loss functions

- chemprop/cli/train.py
- chemprop/nn/predictors.py
- chemprop/nn/transforms.py
Currently, the `output_transform` is applied to every prediction targets for regression tasks. However, the variance for the MVE model and the $\lambda$, $\alpha$, and $\beta$ parameters for the evidential model should be treated differently. Thus, a `transform_variance` function is added to unscale the variance by $\text{scale}^2$. The output transformation is now handled by the `UnscaleTransform` object via PR #726, but the update of output transformation for `MveFFN` and `EvidentialFFN` was missed at that time, so this PR also fixes this. For saving the prediction results, I only save the predicted property values. The other parameters related to uncertainty calculations will be used in prediction CLI with uncertainty methods specified, which will be implemented in PR #937.
> Improve output transformation and prediction saving for `MveFFN` and `EvidentialFFN`

- pyproject.toml
`sphinx-argparse` v0.5.0 has issues that cause it to fail (see https://github.com/sphinx-doc/sphinx-argparse/issues/56) while building docs. This PR forbids that version, and is aimed at avoiding readthedocs from failing while building (which is why other PRs have been failing the readthedocs test). 
I verified that this works locally.
> Fix docs building by pinning sphinx-argparse

- .github/workflows/ci.yml
Our CI is currently failing only on Windows during the Ray tests with this error:
```
2024-07-25 16:38:09,780	ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_49485314
Traceback (most recent call last):
File "C:\Users\runneradmin\micromamba\envs\temp\Lib\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
result = ray.get(future)
^^^^^^^^^^^^^^^
File "C:\Users\runneradmin\micromamba\envs\temp\Lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\runneradmin\micromamba\envs\temp\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix Failing CI for `torch==2.4.0` on Windows `ray[tune]` Tests

- chemprop/nn/loss.py
When running on a GPU, using MCC metrics such as `BinaryMCCMetric()` results in the following error: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
```
188     preds = preds.sigmoid()
190 L = self._calc_unreduced_loss(preds, targets.long(), mask, weights, *args)
--> 191 L = L * self.task_weights
193 return L.mean()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
Retrieve the device information from `preds` and move the tensors to the device using the `to` method.
> Bug: Move `task_weights` to 'device' for MCC metrics

- chemprop/cli/train.py
- docs/source/tutorial/cli/train.rst
The description of training flag `--frzn-ffn-layers` 
https://github.com/chemprop/chemprop/blob/590c32cf14df93bf964d3dac367b202628dd90ea/chemprop/cli/train.py#L112-L117
is incorrect because its actual (and desired) behavior is **freezing** the weights in the first n layers of FFN, instead of **overwritting** them as evident by the following code:
https://github.com/chemprop/chemprop/blob/590c32cf14df93bf964d3dac367b202628dd90ea/chemprop/cli/train.py#L784-L786
Thus, the implementation of `--frzn-ffn-layers` is correct but the description has a typo. This PR fixed this typo. In addition, the corresponding part of the documentation is updated to reflect this change and made more clear.
> Minor: Fix frzn-ffn-layers description and update doc for transfer learning

- chemprop/cli/train.py
Previously, including reaction smiles while enabling `save-smiles-splits` caused chemprop to crash. This is because sometimes reaction SMILES are used to describe datapoints instead of (or in addition to) molecular SMILES.
This changes the `columns` flag when constructing the DataFrame such that the column(s) passed is/are a smiles column, reaction column, or combination of both (depending on whichever ones are present).
Previous question was addressed in latest commits.
#643 was the first to point this out
> V2: Fix `save-smiles-splits` not working with rxn. columns as column header

- chemprop/models/utils.py
- chemprop/utils/v1_to_v2.py
Similar to #950, if a model is trained on a GPU, torch remembers that and when loading onto a cpu only machine, we need to tell it to load onto the CPU. 
Question: In #950 we used `map_location=lambda storage, loc: storage` instead of `map_location=torch.device("cpu")`. Should I do the same thing here?
> Convert v1 models trained on GPU

- chemprop/cli/predict.py
`chemprop predict` command failed if `--no-header-fix` was used with the following error:
>   File "/Users/sunhwan/work/beren/misc/chemprop/chemprop/cli/predict.py", line 297, in make_prediction_for_models
>     df_test[target_columns] = average_preds
>     ~~~~~~~^^^^^^^^^^^^^^^^
>   File "/Users/sunhwan/miniforge3/envs/chemprop/lib/python3.11/site-packages/pandas/core/frame.py", line 4299, in __setitem__
>     self._setitem_array(key, value)
>   File "/Users/sunhwan/miniforge3/envs/chemprop/lib/python3.11/site-packages/pandas/core/frame.py", line 4355, in _setitem_array
>     return self._setitem_array(key, value)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/sunhwan/miniforge3/envs/chemprop/lib/python3.11/site-packages/pandas/core/frame.py", line 4350, in _setitem_array …
> fix no-header-rows in predict command error

- .github/workflows/ci.yml
@jonwzheng pointed out the CI is failing since yesterday. https://github.com/chemprop/chemprop/actions/runs/10716656341/job/29714670717
@JacksonBurns fixed the same issue in #971 by restricting the torch version
@shihchengli also suggests setting `USE_LIBUV` to `0`, or find a way to install PyTorch with `libuv` support on Windows.
Lets see if restricting the torch version works to start.
> change installed torch version on windows actions again

- chemprop/cli/hpopt.py
- examples/hpopting.ipynb
Resolves #1033 - `ray` will make filepaths for saving intermediate results that are too long for Windows. This implements `ray`'s suggested fix, which is to pass a custom 'name-r' for the trials that makes them shorter.
@shihchengli please review
> Fix `hpopting` Notebook and CLI for Windows

- examples/training.ipynb
Addresses issue #820 (https://github.com/chemprop/chemprop/issues/820) 
Currently in `training.ipynb`
```
trainer.test(mpnn, test_loader)
```
Now in `training.ipynb`...
```
trainer.test(dataloaders = test_loader)
```
there is no need to specify the model because the model with the lowest validation loss (can change metric if desired) is automatically selected.
If there are open questions about implementation strategy or scope of the PR, include them here
If appropriate, please tag them here and include a quick summary
> add ModelCheckpointing to training.ipynb so best model is used automatically

- .github/workflows/ci.yml
- chemprop/cli/hpopt.py
- docs/source/installation.rst
- docs/source/tutorial/cli/hpopt.rst
I think [ray](https://docs.ray.io/en/latest/ray-overview/installation.html) now supports python 3.12? 
If the tests run ray on 3.12, then I can also update the documentation to say this works.
> Add ray to tests on python 3 12

- .github/workflows/ci.yml
trying to avoid the continual small patches:
- https://github.com/chemprop/chemprop/pull/1062
- https://github.com/chemprop/chemprop/pull/1016
- https://github.com/chemprop/chemprop/pull/971
based on this part of pytorch docs: https://pytorch.org/tutorials/intermediate/TCPStore_libuv_backend.html#exit-route-3-set-environment-variable-use-libuv-to-0 which was also recommend above in one of these PRs
Just a draft for now - want to see if this works.
> disable libuv with env var rather than avoiding latest torch

- chemprop/uncertainty/__init__.py
- chemprop/uncertainty/calibrator.py
- chemprop/uncertainty/evaluator.py
- chemprop/uncertainty/predictor.py
- tests/unit/uncertainty/test_predictors.py
I went through the uncertainty modules and made some minor changes.
- Improve the formatting of docstrings
- Add `NoUncertaintyPredictor` and `ClassPredictor`
- Comment out `RoundRobinSpectraPredictor`
- Use `logging` instead of `warnings.warn`
> Cleanup the uncertainty modules

- docs/source/tutorial/cli/train.rst
Looking at the docs I realized I said this file is a csv:
It is actually a json file...
> splits file is json

- chemprop/cli/train.py
In the training CLI we have:
https://github.com/chemprop/chemprop/blob/185ab0fda9d63b238ff3f567ae236b40d4769b86/chemprop/cli/train.py#L1261-L1264
This is a problem though because `args.num_replicates` isn't the only way to train on multiple splits of data. The separate splits file can also do that. There will be multiple splitting schemes, but the results will overwrite each other because `num_replicates` is still 1. The splits column in the input data file cannot.
> Fix: Splits file can have multiple splitting schemes

- chemprop/models/model.py
- chemprop/models/multi.py
When `lightning` runs the validation loop, it automatically sets the model to `eval` mode. This is needed to turn off dropout and to tell the batch normalization layer to use its running average statistics instead of batch statistics, the same as is done during inference. 
But this also sets the `output_transform` to `eval`, which would cause the model to unscale the model predictions before comparing with the target values stored in the validation dataset. This is a problem because we made the choice to keep the validation loss in the same scaled space as the training loss so that they would be some what comparable. To do this we scale the target values in the validation dataset, so they should be compared to the raw scaled-space predictions of the model (not the unscaled version). We …
> Set all transforms to train during validation

- chemprop/cli/predict.py
This issue is identified by @jonwzheng. When making predictions with ensembling uncertainty, it would lead to the trace error shown below. This is because Chemprop saves individual prediction results and their corresponding uncertainty values when multiple models are used to make predictions. It is useful for MVE and evidential methods, as each model can have its own predicted uncertainty. However, the ensembling method can only provide one predicted uncertainty across multiple models.
> 2024-11-20T19:42:30 - INFO:chemprop.cli.predict - Predictions saved to 'expt_preds.csv'
> Traceback (most recent call last):
>   File "/home/jonzheng/miniconda3/envs/chemprop/bin/chemprop", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File …
> Fix `save_individual_predictions` with ensembling

- chemprop/data/datapoints.py
- chemprop/utils/utils.py
There have been a number of issues opened in the past which all turned out to be invalid SMILES strings:
- https://github.com/chemprop/chemprop/issues/965
- https://github.com/chemprop/chemprop/issues/1122
- https://github.com/chemprop/chemprop/issues/1044
We currently report the following slightly unhelpful error:
```python
ValueError: Input molecule was `None`!
```
This PR adds a check in `make_mol` to see if `Chem.MolFromSmiles` returns `None`, and then prints the corresponding SMILES.
We could probably then safely delete the check for `None`, elsewhere, if we want to.
See top.
Edited this in the browser, will let the CI check these.
> Add a helpful warning when invalid SMILES are passed

- chemprop/nn/agg.py
Closes #1120 
The AttentiveAggregation class uses a single learned linear layer to calculate what the weight of each node should be in aggregation based on the node's learned representation. I don't see this as an option in v1, so I think it is new to v2, but I don't really know its background.
In any event, it needs to know what the length of the node representation is so it can instantiate a linear layer. We need to save this length as a hyperparameter under aggregation so that we can reload it from a checkpoint.
> Add output size to attentive hparams

- .github/workflows/ci.yml
- chemprop/cli/predict.py
- environment.yml
- pyproject.toml
- tests/unit/featurizers/test_molecule.py
- tests/unit/uncertainty/test_calibrators.py
Replaces #1187 
Changes:
- allow any numpy version (resolves #1186)
- weakens expected reproducibility one of our numbers from e-7 to e-4
- runs ci on macos intel chips with conda instead of pip, since conda has the latest torch binaries compatible for intel macs but pip doesn't
- update environment file to get torch from conda-forge
> Allow Numpy 2+

- chemprop/cli/common.py
- chemprop/cli/fingerprint.py
- chemprop/cli/hpopt.py
- chemprop/cli/predict.py
- chemprop/cli/train.py
- chemprop/cli/utils/parsing.py
- chemprop/data/datapoints.py
- chemprop/utils/utils.py
- docs/source/tutorial/python/featurizers/molecule_featurizers.ipynb
- tests/cli/test_cli_classification_mol.py
- tests/unit/data/test_datapoint.py
- tests/unit/featurizers/test_cgr.py
Addresses #1076, #1077, and #1078.
This PR adds the CLI option `--ignore-chirality` to be used in all commands (`train`, `predict`, etc.).
The solution is analogous to the implementation of `--add-h` and `--keep-h`: a new argument was added to class methods that instantiate datapoints from SMILES strings. **Note**: like `--add-h` and `--keep-h`, `--ignore-chirality` shows up in the CLI help as a featurization option.
> Adds CLI option to ignore chirality in SMILES

- chemprop/cli/utils/parsing.py
As suggested in #1199 to fix #1199
In the CLI, we do some string operations on bounded targets to see if they have a "<" or ">". This only works if all the entries in the DataFrame are strings. In #1199, the user had some missing target values which `pandas` will read in as `np.nan` which is a float. This nan value will stay a float even if the rest of the rows in the column are strings. Compare this to normal floats like `1.1` which are converted to (or actually left as) strings like `"1.1"` if there are other values in the column that can't be converted to floats. 
Using `Y = Y.astype(str)` will convert `np.nan` into `"nan"`. This lets the string operations work. Then `Y = Y.to_numpy(np.single)` will cast the `"nan"` back to `np.nan` (but as a float32). 
There could also be a problem if …
> Make sure bounded targets dataframe is all strings

- chemprop/uncertainty/estimator.py
- tests/cli/test_cli_regression_mol.py
Fixes #1204
In #1055, we changed `DropoutEstimator` to work for multiple models, with the idea that dropout would be used with each model to get a prediction and uncertainty estimate for each model, which would be individually written to the `preds_individual.csv` and then averaged to be written in `preds.csv`. But when we added `torch.stack(meanss)` to get the `n_datapoints x n_targets` preds into an `n_models x n_datapoints x n_targets` tensor, we forgot that the preds tensors already were shape `1 x n_datapoints x n_targets` (because we only supported one model) by using unsqueeze: `means = torch.mean(stacked_preds, dim=0).unsqueeze(0)`. Removing the unsqueeze gets the output tensor in the expected shape. 
I also added a CLI test for dropout and ensembling.
> Fix dropout uncertainty output shape

- chemprop/cli/utils/parsing.py
- chemprop/nn/metrics.py
The (data point) weights passed to a loss function/metric should be shape `batch_size` or `batch_size x 1` as noted in the base class doc string:
https://github.com/chemprop/chemprop/blob/ba7a496d1b98ae81aaced867f0bd0320649c74e8/chemprop/nn/metrics.py#L97-L98
We had typo in parsing, but more importantly the default weights array in the metrics is shape `batch_size x n_tasks`, which will be an issue when we try to unsqueeze the weights using `weights.view(-1, 1)`.
> (Data point) weights should be shape `b` or `b x 1`

- .flake8
- .gitignore
- chemprop/cli/train.py
- chemprop/utils/utils.py
- docs/source/chemeleon_foundation_finetuning.nblink
- docs/source/notebooks.rst
- docs/source/tutorial/cli/train.rst
- examples/chemeleon_foundation_finetuning.ipynb
- pyproject.toml
- tests/cli/test_cli_regression_mol.py
This pull request implements support for finetuning foundation models in `ChemProp` via the Command Line Interface (CLI), which was not previously possible.
A demo notebook for the same, but via the Python module interface, is also added.
Finally, support for the [`CheMeleon`](https://github.com/JacksonBurns/chemeleon) model by myself and @akshatzalte is also added.
Right now, ChemProp supports transfer learning in which a model is trained and then fine-tuned on the _same_ task. This does **not** allow the user to change the architecture during finetuning.
It is desirable to re-use only the learned representation and to create a new FFN that applies to some entirely new task. This is currently not possible via the CLI for ChemProp. It is possible via Python Modules, but we don't have a …
> Add Support for Fine-Tuning Foundation Models with `--from-foundation` and add `CheMeleon`

- chemprop/cli/train.py
resolves https://github.com/chemprop/chemprop/issues/1221 by ensuring that, when attempting to load pretrained scalers from models, we place the models on the CPU s.t. the scalers that we are rebuilding can interact with them (the new scalers are also on the CPU)
> Ensure `device="cpu"` when loading Scalers

- chemprop/__init__.py
The `uncertainty` subpackage is missing from `chemprop.__all__`, which causes the following statements to fail:
```py
from chemprop import uncertainty
```
```py
import chemprop
estimator = chemprop.uncertainty.EnsembleEstimator()
```
This PR adds `uncertainty` to `chemprop.__all__`.
> Allow importing uncertainty as a subpackage

- docs/source/tutorial/cli/train.rst
- tests/cli/test_cli_regression_mol.py
Refactor the splits.json file used in both tutorial & testing to follow 0-indexing.
The current splits.json assigned indices 1 through 7 to train/val/test sets, which is misleading toward an assumption that the splitting module expect 1-indexing, while in reality the model operates on 0-indexing and using 1-indexing can lead to assignment offset and index-out-of-range error. This issue has not been exposed in prior testing because datasets used for testing generally have size greater than 8, yet error would occur if we run the split on a dataset of exactly 7 elements.
Modified splits.json to assign indices 0 through 5 instead, in accordance with the 0-index pipeline.
N/A
N/A
- [Yes] linted with flake8?
> Zero-indexing refactoring of splits.json used in both tutorial & test

- MANIFEST.in
- pyproject.toml
our previous build attempt got rejected for being too large (130 MB with a limit of 100 MB). remove these files wich are not needed anyway
Build failure is here: https://github.com/chemprop/chemprop/actions/runs/15331593506/job/43143986608#step:6:230
> remove unneeded folders from python distrubution

- tests/cli/test_cli_regression_mol.py
- tests/integration/test_regression_MAB.py
Fix the test_overfit function in chemprop/tests/integration/test_regression_MAB.py.
The current test_overfit is non-deterministic, sometimes producing MSE above the 0.01 threshold, leading to random test failures.
The fix is to set the seed before initializing parameters of the test. After doing so, test_overfit produces deterministic MSE values, even when the tests are reordered.
N/A
N/A
- [Yes] linted with flake8?
- [N/A] unit tests added?
> Fix randomly failing overfit test

- chemprop/cli/hpopt.py
- chemprop/cli/train.py
- chemprop/conf.py
Right now `chemprop hpopt` will overwrite the choice of `CheMeleon` as the foundation model. This is because `build_model` expects the `from_foundation` argument, rather than just getting it from `args` (I did it this way for some ill-conceived reason).
- change how `build_model` checks for foundation models
- remove some params from the search space when using a foundation model since they don't change
- remove import from `conf.py` to avoid circular import when attempting to unpickle the chemeleon `.pt` during ray hpopt (retains compatibility with current usage - the entered values are what they were, just hardcoded)
Didn't open one to track, but found it while investigating #1272
> Bug Fix: Add handling for `--from-foundation` argument in `hpopt`

- chemprop/cli/train.py
- chemprop/data/splitting.py
- tests/cli/test_cli_regression_mol.py
Add support for empty/null test set for data input, by exchanging val and test arguments in splitting.py, and checking emptiness of test arguments before indexing in train.py.
The current workflow disallows empty test set - ie. having a train-val-test split of 0.5-0.5-0 triggers an error.
The new workflow handles empty test set - ie. 0.5-0.5-0 split - without error, and trains upon the resulting train/val sets as intended.
N/A
#1165
- [Yes] linted with flake8?
> Add support for empty test set

- chemprop/cli/hpopt.py
- chemprop/cli/train.py
Changes hyperparameter optimization to use the given `--tracking-metric` to decide on the best trial, rather than using the metric used for training.
Currently, the `--tracking-metric` is used to control early stopping and model checkpointing, but is not used to decide which hyperparameter configuration during hyperparameter optimization is the best (`hpopt` instead uses the training metric).
The above is changed by moving some of the logic checking the tracking metric around.
Works locally (I was able to set the hpopt tracking metric via the CLI) just need to get CI running.
Closes #1254
> make `hpopt` use `--tracking-metric`

- chemprop/cli/common.py
- chemprop/cli/fingerprint.py
- chemprop/cli/predict.py
- chemprop/cli/train.py
- chemprop/cli/utils/MAB_parsing.py
- chemprop/cli/utils/parsing.py
- chemprop/data/datasets.py
- chemprop/featurizers/molecule.py
- chemprop/featurizers/molgraph/cache.py
- chemprop/utils/__init__.py
- chemprop/utils/utils.py
- docs/source/tutorial/cli/train.rst
- docs/source/tutorial/python/data/datasets.ipynb
- tests/cli/test_cli_regression_mol+mol.py
- tests/unit/utils/test_multiprocess.py
Large datasets (100k+ molecules) are slow to load. This PR leverages multiprocessing to load and featurize molecules faster if applicable.
With old code loading molecules and constructing graphs with following parameters: 
> chemprop train -i my_big_file.csv --num-workers 0 
is as slow as with: 
> chemprop train -i my_big_file.csv --num-workers 16
This PR speeds up the loading if `--num-workers` is increased. 
N.A.
N.A.
N.A.
> Allow multiprocess loading.
