web/app/templates/home.html, web/app/templates/layout.html, web/app/templates/predict.html, web/app/views.py, web/config.py, web/run.py
Introduced 'DEMO' config variable, which decides whether all site features should be displayed.
=> Add DEMO Config Variable

web/app/templates/macros.html, web/app/views.py
Enable uploading of ensembles of models to the website as .zip files
=> Enable uploading of ensembles to the website

scripts/find_similar_mols.py
Adding Tanimoto similarity to the find similar mols helper script.
=> Adding tanimoto similarity calc

chemprop/web/app/views.py
run_train should get data argument as list.
=> fix view_bug

chemprop/__init__.py, chemprop/web/config.py
See https://github.com/chemprop/chemprop/issues/84
=> allow loading after global installation

README.md
This fixes the URL problem described in issue #96
=> Small fix for README.md

README.md, docs/source/tutorial.rst
Updated README.md and the documentation (tutorial.rst) to include information about using additional atomic features.
=> Updated README and docs

chemprop/sklearn_train.py
Bugfix for scores in chemprop/train_sklearn.py as suggested by @phseidl in [PR 126](https://github.com/chemprop/chemprop/pull/126) and including the changes we suggested but weren't made yet to [PR 126](https://github.com/chemprop/chemprop/pull/126).
=> bugfix sklearn

chemprop/args.py, chemprop/models/model.py, chemprop/nn_utils.py, chemprop/train/run_training.py, chemprop/utils.py
This update is to allow users to freeze mpnn/ffn layers for pretraining. I'm not sure what additional info is needed so let me know if you need anything else for this pull request. Thanks!
=> Mpnnfreeze

chemprop/train/train.py
Fix an issue with the new data_weights feature where it was causing errors when used with gpu's.
=> Hotfix for data weights with cuda support

chemprop/_version.py, docs/source/conf.py
I don't have permissions to push this directly, need to go through a PR. Incrementing version number for release 1.3.1.
=> Increment Version Number

chemprop/_version.py, docs/source/conf.py
Incrementing version number with forthcoming release.
=> Update version number for new release 1.4.0

chemprop/args.py, chemprop/data/data.py, chemprop/data/scaffold.py, chemprop/features/__init__.py, chemprop/features/featurization.py, chemprop/rdkit.py, chemprop/train/cross_validate.py, chemprop/train/make_predictions.py, chemprop/train/molecule_fingerprint.py
Simple PR to add the functionality of allowing the user to specify if they want to have the smiles molecules be parametrized with or without Hydrogens.
=> Adding function to be able add Hydrogens to the rdkit mol

chemprop/utils.py
modernizes the `chemprop.utils` module
- raises generic Exceptions in some places
- hard-to-parse, very long lines
- uses `str.format()`
- uses bitwise operators in place of logical operators
- changes `Exception`s to more descriptive `ValueError`s
- breaks up long lines into multi-line expressions
- switches over to using f-strings
- corrects the bitwise operators to logical operators
there's the general question here of developing custom exceptions to more succinctly capture errors in client calls, but that's outside the scope of this PR
=> update utils module

README.md, docs/source/tutorial.rst
This PR fixes broken links to MoleculeNet.
=> Fix broken MoleculeNet links

scripts/tsne.py
Fixes #402 by making np.array from list, per user suggestion. See issue for more details.
=> Fix t-SNE script

chemprop/v2/data/dataloader.py, chemprop/v2/tests/unit/data/test_dataloader.py, tests/unit/data/test_dataloader.py
1. Fixed a bug where wrong variables were assigned when unpacking Datum. Specifically, `lt_masks` should have higher precedence than `gt_masks` based on the definition in Datum class.
2. Added initial unit tests for dataloader in chemprop v2. This improves coverage from 0% to 62%. Will add more in later commits.
=> Fix bug and add unit test for dataloader v2

chemprop/v2/data/datasets.py, examples/training.ipynb
@kevingreenman and @KnathanM mentioned that it would be great if we can add a jupyter notebook for training. I adapt the `example.py` file into a jupyter notebook and add comments.
=> Jupyter notebook to train v2 model and debug scaler

.github/ISSUE_TEMPLATE/todo.md
Adds a new issue template, "[TODO]"
These are for more general items that developers want to keep track of (e.g., updating author lists, pruning branches, etc.)
=> Add `todo.md`

examples/predicting.ipynb
I added an example notebook to make predictions from a trained MPNN for a single component regression task.
=> V2: Add example notebook for predicting

chemprop/v2/data/utils.py, chemprop/v2/tests/unit/data/test_data_utils.py
Refactored tests for data split for chemprop v2.
=> V2: Refactor tests for data split

chemprop/v2/cli/train.py, chemprop/v2/data/collate.py
This continues the efforts in https://github.com/chemprop/chemprop/pull/549 to make the unit tests pass for v2. The fix is cherry-picked from https://github.com/chemprop/chemprop/commit/753d05c17af7dd48cebc45de4bc5ede517e5d1a2 of https://github.com/chemprop/chemprop/pull/470.
=> V2: Fix concatenation bug in collate_batch function and argument processing

chemprop/data/__init__.py, chemprop/data/collate.py, chemprop/models/model.py, chemprop/models/multi.py, chemprop/nn/message_passing/multi.py
Fix some bugs identified when working on https://github.com/chemprop/chemprop/pull/500, including imports and unify parameter names.
=> V2: fix multicomponent bugs

.github/workflows/tests.yml, examples/predicting_regression_multicomponent.ipynb, examples/training_regression_multicomponent.ipynb
Add an example notebook for training multicomponent MPNN for regression task. Currently blocked by https://github.com/chemprop/chemprop/pull/522 and https://github.com/chemprop/chemprop/pull/521.
=> Add example notebook for training and predicting multicomponent regression

.github/workflows/tests.yml, chemprop/cli/main.py, chemprop/cli/predict.py, chemprop/cli/train.py, chemprop/cli/utils/command.py, chemprop/cli/utils/conf.py, chemprop/cli/utils/parsing.py, chemprop/data/datasets.py, chemprop/featurizers/molgraph/reaction.py, pyproject.toml
This PR works on #561 by fixing parts of the CLI that worked before and adding some CLI integration tests. This PR is to just get the basic CLI working again. Future PRs will add more features to the CLI and tests for them. 
The CLI was last worked on in early October. There have been many changes to the code since then and new abilities added. We have focused on making the code work in a notebook setting but also want the code to be accessible from the command line. 
We want command line users to be able to access most if not all of the code features. We also want to make it easy for v1 users to switch their workflows to v2. As such we are keeping track of CLI changes in this spreadsheet: https://docs.google.com/spreadsheets/d/1PxfHrxqD_XmY4IfoTat0HnkJrGKKRTg_oyfalOVNNXg/edit#gid=0
=> CLI Improvements

chemprop/data/splitting.py
From discussion in https://github.com/chemprop/chemprop/issues/581#issuecomment-1911008302, I realize that the implementation of cross validation in `data_split` is not one usually expects. I make this PR to start a conversation on how we should implement it. @JacksonBurns please let me know if you think this makes sense. 
This should close https://github.com/chemprop/chemprop/issues/609.
=> V2: fix cross validation in `data_split`

chemprop/cli/common.py, docs/source/tutorial/cli/train.rst
Do these changes to the docs look good @kevingreenman ?
=> update training docs

tests/regenerate_models.sh
Sometimes we need to regenerate example model files when we make module level changes. It can be annoying to do so manually every time. I added a script to update all example model files used in tests automatically.
=> Add a script to regenerate all example model files for test

examples/convert_v1_to_v2.ipynb, examples/extra_features_from_featurizer.ipynb, examples/mpnn_fingerprints.ipynb, examples/predicting.ipynb, examples/predicting_regression_multicomponent.ipynb, examples/predicting_regression_reaction.ipynb, examples/training.ipynb, examples/training_regression_multicomponent.ipynb, examples/training_regression_reaction.ipynb
This PR updates the paths in the example notebooks to make use of `pathlib` to be more system-agnostic in order to address #687. @Olivierj23 made the changes to address this issue but ran into some git issues, so I'm opening the PR on his behalf. 
#687
=> Update example notebooks to use pathlib

Dockerfile
@KnathanM and I did this offline.
=> Change Docker sytnax for MyBinder compatibility

chemprop/cli/fingerprint.py, chemprop/cli/hpopt.py, chemprop/cli/train.py, tests/cli/test_cli_regression_mol.py
The featurizer needs to be constructed in hpopt and fingerprint, similar to what we do in train.
See https://github.com/chemprop/chemprop/issues/864.
I construct the featurizer in hpopt and fingerprint as we do in train. I also add cli tests for them.
n/a
https://github.com/chemprop/chemprop/issues/864
=> [V2] Fix featurizer cli

chemprop/cli/predict.py
=> Fix the inference issue related to the target columns

chemprop/models/model.py, chemprop/models/multi.py
=> Pass `map_location` through `load_submodules()` to `torch.load()`

examples/training_classification.ipynb
##Description
Example notebook of classification in regards to Issue https://github.com/chemprop/chemprop/issues/1030, pretty much similar to workflow for regression but with some changes in normalization and FFN.
##Questions
Since I ran tests on my m2, I used accelerator as cpu due to low MPS ops coverage, but probably could be changed to "auto"
=> Example Notebook for Classification

chemprop/uncertainty/calibrator.py, tests/unit/uncertainty/test_calibrators.py
This reimplements Isotonic calibrators from v1
=> add isotonic calibrators

.github/workflows/ci.yml
The same issue that was identified before (#971 , #1016)
=> change installed torch version on windows actions again

chemprop/cli/convert.py, chemprop/utils/v1_to_v2.py
Edits the conversion from v1 to v2 model checkpoints so that it is now a .pt file instead of .ckpt file. 
Closes #945
=> .pt instead of .ckpt

docs/source/tutorial/cli/train.rst
I read through most of the readthedocs and only saw a couple things that were incorrect.
=> update train docs for v2.1

chemprop/data/splitting.py
=> add more helpful warnings about the splitting api change

chemprop/cli/train.py
=> Fix `tracking_metric` overwrite issue

chemprop/nn/predictors.py, tests/integration/conftest.py, tests/integration/test_regression_mol.py
=> Not use `transform_variance` for unscaled targets

chemprop/cli/train.py
=> Apply task_weights to default loss function in CLI

chemprop/uncertainty/estimator.py
=> Check if dropout prop needs to be restored

environment.yml, pyproject.toml
=> Allow numpy 2+

README.md, chemprop/cli/fingerprint.py, chemprop/cli/predict.py, chemprop/cli/train.py, docs/source/installation.rst, docs/source/tutorial/cli/train.rst, examples/training.ipynb, requirements/get_requirements.sh
Replacing all instances of 'ChemProp' with 'Chemprop' in the repo.
=> Standardizing the name Chemprop

.github/workflows/ci.yml, chemprop/nn/metrics.py
This PR fixes device allocation issues in PyTorch tensor creation within the metrics module. The fix ensures that newly created weight tensors are placed on the same device as the target tensors, preventing potential device mismatch errors during tensor operations.
Include a sample workflow to either **(a)** reproduce the bug with current codebase or **(b)** showcase the deficiency does this PR seeks to address
```python
from chemprop.nn import BinaryClassificationFFN
from chemprop.nn.metrics import BCELoss
task_dim = 3
predictor = BinaryClassificationFFN(
n_tasks=task_dim,
criterion=BCELoss(task_weights=torch.ones(task_dim)),
)
device = "mps"
predictor.to(device=device)
predictor.criterion(
torch.ones((10, task_dim)).to(device=device),
torch.ones((10, task_dim)).to(device=device)
)
>>> …
```
=> Fix device allocation in metrics weights
